
#   Author:     SYEED MOHD AMEEN                                    Date:   19-09-2020
#   Email:      ameensyeed2@gmail.com
#   License:    GPLv3



#------------------------------------------------------------#
#                       Opcode Table                         #
#------------------------------------------------------------#


accumulator         = 0
reg                 = 1
i_reg               = 2 
page_address        = 3 
address_16_bit      = 4 
data_16_bit         = 5 
accumulator         = 6 
bit_address         = 7 
relative_address    = 8 
iram_address        = 9 
carry               = 10 
immediate_data      = 11 
i_acc_pl_dptr       = 12 
i_acc_pl_pc         = 13
i_dptr              = 14
Breg                = 15 
dptr                = 16 



opcode = {
        '0':('nop',        0,                     0,0,0),
        '1':('ajmp',      page_address                ),
        '2':('ljmp',      address_16_bit              ),
        '3':('rr',        accumulator                 ),
        '4':('inc',       accumulator                 ),
        '5':('inc',       iram_address                ),
        '6':('inc',       i_reg,                      0),
        '7':('inc',       i_reg,                      1),
        '8':('inc',       reg,                        0),
        '9':('inc',       reg,                        1),
        'A':('inc',      reg,                        2),

        'B':('inc',      reg,                        3),
        'C':('inc',      reg,                        4),
        'D':('inc',      reg,                        5),
        'E':('inc',      reg,                        6),
        'F':('inc',      reg,                        7),
        '10':('jbc',      bit_address,                relative_address),
        '11':('acall',    page_address                ),
        '12':('lcall',    address_16_bit              ),
        '13':('rrc',      accumulator                 ),
        '14':('dec',      accumulator                 ),

        '15':('dec',      iram_address                ),
        '16':('dec',      i_reg,                      0),
        '17':('dec',      i_reg,                      1),
        '18':('dec',      reg,                        0),
        '19':('dec',      reg,                        1),
        '1A':('dec',      reg,                        2),
        '1B':('dec',      reg,                        3),
        '1C':('dec',      reg,                        4),
        '1D':('dec',      reg,                        5),
        '1E':('dec',      reg,                        6),

        '1F':('dec',      reg,                        7),
        '20':('jb',       bit_address,                relative_address),
        '21':('ajmp',     page_address                ),
        '22':('ret'                                   ),
        '23':('rl',       accumulator                 ),
        '24':('add',      accumulator,                immediate_data),
        '25':('add',      accumulator,                iram_address),
        '26':('add',      accumulator,                i_reg,0),
        '27':('add',      accumulator,                i_reg,1),
        '28':('add',      accumulator,                reg,0),

        '29':('add',      accumulator,                reg,1),
        '2A':('add',      accumulator,                reg,2),
        '2B':('add',      accumulator,                reg,3),
        '2C':('add',      accumulator,                reg,4),
        '2D':('add',      accumulator,                reg,5),
        '2E':('add',      accumulator,                reg,6),
        '2F':('add',      accumulator,                reg,7),
        '30':('jnb',      bit_address,                relative_address),
        '31':('acall',    page_address                ),
        '32':('reti'                                  ),

        '33':('rcl',      accumulator                 ),
        '34':('addc',     accumulator,                immediate_data),
        '35':('addc',     accumulator,                iram_address),
        '36':('adcc',     accumulator,                i_reg,0),
        '37':('adcc',     accumulator,                i_reg,1),
        '38':('adcc',     accumulator,                reg,0),
        '39':('adcc',     accumulator,                reg,1),
        '3A':('adcc',     accumulator,                reg,2),
        '3B':('adcc',     accumulator,                reg,3),
        '3C':('adcc',     accumulator,                reg,4),

        '3D':('adcc',     accumulator,                reg,5),
        '3E':('adcc',     accumulator,                reg,6),
        '3F':('adcc',     accumulator,                reg,7),
        '40':('jc',       relative_address            ),
        '41':('ajmp',     page_address                ),
        '42':('orl',      iram_address,               accumulator),
        '43':('orl',      iram_address,               immediate_data),
        '44':('orl',      accumulator,                immediate_data),
        '45':('orl',      accumulator,                iram_address),
        '46':('orl',      accumulator,                i_reg,0),

        '47':('orl',      accumulator,                i_reg,1),
        '48':('orl',      accumulator,                reg,0),
        '49':('orl',      accumulator,                reg,1),
        '4A':('orl',      accumulator,                reg,2),
        '4B':('orl',      accumulator,                reg,3),
        '4C':('orl',      accumulator,                reg,4),
        '4D':('orl',      accumulator,                reg,5),
        '4E':('orl',      accumulator,                reg,6),
        '4F':('orl',      accumulator,                reg,7),
        '50':('jnc',      relative_address            ),

        '51':('acall',    page_address                ),
        '52':('anl',      iram_address,               accumulator),
        '53':('anl',      iram_address,               immediate_data),
        '54':('anl',      accumulator,                immediate_data),
        '55':('anl',      accumulator,                iram_address),
        '56':('anl',      accumulator,                i_reg,0),
        '57':('anl',      accumulator,                i_reg,1),
        '58':('anl',      accumulator,                reg,0),
        '59':('anl',      accumulator,                reg,1),
        '5A':('anl',      accumulator,                reg,2),

        '5B':('anl',      accumulator,                reg,3),
        '5C':('anl',      accumulator,                reg,4),
        '5D':('anl',      accumulator,                reg,5),
        '5E':('anl',      accumulator,                reg,6),
        '5F':('anl',      accumulator,                reg,7),
        '60':('jz',       relative_address            ),
        '61':('ajmp',     page_address                ),
        '62':('xrl',      iram_address,               accumulator),
        '63':('xrl',      iram_address,               immediate_data),
        '64':('xrl',     accumulator,                immediate_data),

        '65':('xrl',     accumulator,                iram_address),
        '66':('xrl',     accumulator,                i_reg,0),
        '67':('xrl',     accumulator,                i_reg,1),
        '68':('xrl',     accumulator,                reg,0), 
        '69':('xrl',     accumulator,                reg,1),
        '6A':('xrl',     accumulator,                reg,2),
        '6B':('xrl',     accumulator,                reg,3),
        '6C':('xrl',     accumulator,                reg,4),
        '6D':('xrl',     accumulator,                reg,5),
        '6E':('xrl',     accumulator,                reg,6),

        '6F':('xrl',     accumulator,                reg,7),
        '70':('jnz',     relative_address            ),
        '71':('acall',   page_address                ),
        '72':('orl',     carry,                      bit_address),
        '73':('jmp',     i_acc_pl_dptr               ),
        '74':('mov',     accumulator,                immediate_data),
        '75':('mov',     iram_address,               immediate_data),
        '76':('mov',     i_reg,                      immediate_data,0),
        '77':('mov',     i_reg,                      immediate_data,1),
        '78':('mov',     reg,                        immediate_data,0),

        '79':('mov',     reg,                        immediate_data,1),
        '7A':('mov',     reg,                        immediate_data,2),
        '7B':('mov',     reg,                        immediate_data,3),
        '7C':('mov',     reg,                        immediate_data,4),
        '7D':('mov',     reg,                        immediate_data,5),
        '7E':('mov',     reg,                        immediate_data,6),
        '7F':('mov',     reg,                        immediate_data,7),
        '80':('sjmp',    relative_address            ),
        '81':('ajmp',    page_address                ),
        '82':('anl',     carry,                      bit_address),

        '83':('movc',    accumulator,                i_acc_pl_pc),
        '84':('div',     accumulator,                Breg),
        '85':('mov',     iram_address,               iram_address),
        '86':('mov',     iram_address,               i_reg,0),
        '87':('mov',     iram_address,               i_reg,1),
        '88':('mov',     iram_address,               reg,0),
        '89':('mov',     iram_address,               reg,1),
        '8A':('mov',     iram_address,               reg,2),
        '8B':('mov',     iram_address,               reg,3),

        '8C':('mov',     iram_address,               reg,4),
        '8D':('mov',     iram_address,               reg,5),
        '8E':('mov',     iram_address,               reg,6),
        '8F':('mov',     iram_address,               reg,7),
        '90':('mov',     dptr,                       data_16_bit),
        '91':('acall',   page_address                ),
        '92':('mov',     bit_address,                carry),
        '93':('movc',    accumulator,                i_acc_pl_dptr),
        '94':('subb',    accumulator,                immediate_data),
        '95':('subb',    accumulator,                iram_address),
        '96':('subb',    accumulator,                i_reg,0),
        '97':('subb',    accumulator,                i_reg,1),
        '98':('subb',    accumulator,                reg,0),
        '99':('subb',    accumulator,                reg,1),
        '9A':('subb',    accumulator,                reg,2),
        '9B':('subb',    accumulator,                reg,3),
        '9C':('subb',    accumulator,                reg,4),
        '9D':('subb',    accumulator,                reg,5),
        '9E':('subb',    accumulator,                reg,6),
        '9F':('subb',    accumulator,                reg,7),
        'A0':('orl',     carry,                      bit_address),

        'A1':('ajmp',    page_address                ),
        'A2':('mov',     carry,                      bit_address),
        'A3':('inc',     dptr                        ),
        'A4':('mul',     accumulator,                Breg),
        'A5':('reserved',0,0,0),         
        'A6':('mov',     i_reg,                      iram_address,0),
        'A7':('mov',     i_reg,                      iram_address,1),
        'A8':('mov',     reg,                        iram_address),
        'A9':('mov',     reg,                        iram_address,1),
        'AA':('mov',     reg,                        iram_address,2),

        'AB':('mov',     reg,                        iram_address,3),
        'AC':('mov',     reg,                        iram_address,4),
        'AD':('mov',     reg,                        iram_address,5),
        'AE':('mov',     reg,                        iram_address,6),
        'AF':('mov',     reg,                        iram_address,7),
        'B0':('anl',     carry,                      bit_address),
        'B1':('acall',   page_address                ),
        'B2':('cpl',     bit_address                 ),
        'B3':('cpl',     carry                       ),
        'B4':('cjne',    accumulator,                immediate_data,relative_address),

        'B5':('cjne',    accumulator,                iram_address,relative_address),
        'B6':('cjne',    i_reg,                      immediate_data,relative_address,0),
        'B7':('cjne',    i_reg,                      immediate_data,relative_address,1),
        'B8':('cjne',    reg,                        immediate_data,relative_address,0),
        'B9':('cjne',    reg,                        immediate_data,relative_address,1),
        'BA':('cjne',    reg,                        immediate_data,relative_address,2),
        'BB':('cjne',    reg,                        immediate_data,relative_address,3),
        'BC':('cjne',    reg,                        immediate_data,relative_address,4),
        'BD':('cjne',    reg,                        immediate_data,relative_address,5),
        'BE':('cjne',    reg,                        immediate_data,relative_address,6),
        'BF':('cjne',    reg,                        immediate_data,relative_address,7),
        'C0':('push',    iram_address                ),
        'C1':('ajmp',    page_address                ),
        'C2':('clr',     bit_address                 ),
        'C3':('clr',     carry                       ),
        'C4':('swap',    accumulator                 ),
        'C5':('xch',     accumulator,                iram_address),
        'C6':('xch',     accumulator,                i_reg,0),
        'C7':('xch',     accumulator,                i_reg,1),
        'C8':('xch',     accumulator,                reg,0),

        'C9':('xch',     accumulator,                reg,1),
        'CA':('xch',     accumulator,                reg,2),
        'CB':('xch',     accumulator,                reg,3),
        'CC':('xch',     accumulator,                reg,4),
        'CD':('xch',     accumulator,                reg,5),
        'CE':('xch',     accumulator,                reg,6),
        'CF':('xch',     accumulator,                reg,7),
        'D0':('pop',     iram_address                ),
        'D1':('acall',   page_address                ),
        'D2':('setb',    bit_address                 ),

        'D3':('setb',    carry                       ),
        'D4':('da a'                                 ),
        'D5':('djnz',    iram_address,               relative_address),
        'D6':('xchd',    accumulator,                i_reg,0),
        'D7':('xchd',    accumulator,                i_reg,1),
        'D8':('djnz',    reg,                        relative_address,0),
        'D9':('djnz',    reg,                        relative_address,1),
        'DA':('djnz',    reg,                        relative_address,2),
        'DB':('djnz',    reg,                        relative_address,3),
        'DC':('djnz',    reg,                        relative_address),
        'DD':('djnz',    reg,                        relative_address,5),
        'DE':('djnz',    reg,                        relative_address,6),
        'DF':('djnz',    reg,                        relative_address,7),
        'E0':('movx',    accumulator,                i_dptr),
        'E1':('ajmp',    page_address                ),
        'E2':('movx',    accumulator,                i_reg,0),
        'E3':('movx',    accumulator,                i_reg,1),
        'E4':('clr',     accumulator                 ),
        'E5':('mov',     accumulator,                iram_address),
        'E6':('mov',     accumulator,                i_reg,0),

        'E7':('mov',     accumulator,                i_reg,1),
        'E8':('mov',     accumulator,                reg,0),
        'E9':('mov',     accumulator,                reg,1),
        'EA':('mov',     accumulator,                reg,2),
        'EB':('mov',     accumulator,                reg,3),
        'EC':('mov',     accumulator,                reg,4),
        'ED':('mov',     accumulator,                reg,5),
        'EE':('mov',     accumulator,                reg,6),
        'EF':('mov',     accumulator,                reg,7),
        'F0':('movx',    i_dptr,                     accumulator),

        'F1':('acall',   page_address                ),
        'F2':('movx',    i_reg,                      accumulator,0),
        'F3':('movx',    i_reg,                      accumulator,1),
        'F4':('cpl',     accumulator                 ),
        'F5':('mov',     iram_address,               accumulator),
        'F6':('mov',     i_reg,                      accumulator,0),
        'F7':('mov',     i_reg,                      accumulator,1),
        'F8':('mov',     reg,                        accumulator,0),
        'F9':('mov',     reg,                        accumulator,1),
        'FA':('mov',     reg,                        accumulator,2),

        'FB':('mov',     reg,                        accumulator,3),
        'FC':('mov',     reg,                        accumulator,4),
        'FD':('mov',     reg,                        accumulator,5),
        'FE':('mov',     reg,                        accumulator,6),
        'FF':('mov',     reg,                        accumulator,7),
        
}


if __name__ == "__main__":
        print("This is Python Module ")
        print("Run Assembler.py")    